[WIP]コメント投稿機能(Comments.index)
ozeryu7/tenkue-board-r006 pull request #12
Opened 2020-11-03 08:58 UTC by tattu501

#何か
掲示板詳細ページにコメント投稿機能を追加

2020-11-03 10:38 UTC, nousi requested changes

2020-11-03 10:38 UTC, nousi commented on app/assets/stylesheets/comments.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
使用していないので削除

2020-11-03 10:38 UTC, nousi commented on app/controllers/comments_controller.rb
> +  def create
`before_action :authenticate_user!`の追加をしておきましょう

2020-11-03 10:38 UTC, nousi commented on app/views/posts/show.html.erb
> +              <%= f.hidden_field :post_id, value: @post.id %>
これらは削除して、コントローラーで処理をしましょう

この方法もとても面白いと思いますが、user_idとposts_idをhtml上に表示させてしまうので、セキュリティ面で不安が残ると思います。
また、html上でuser_idとpost_idの数字を変更すれば、「別の投稿に、別のuserで投稿できてしまう」ので、避けるべき手法だと思います。

2020-11-03 10:38 UTC, nousi commented on app/controllers/comments_controller.rb
> +    @comment = current_user.comments.new(comment_params)
`@comment = @post.comment.new(comment_params)`
で定義しましょう

2020-11-03 10:38 UTC, nousi commented on app/controllers/comments_controller.rb
> +      params.require(:comment).permit(:comment, :user_id, :post_id)
`params.require(:comment).permit(:comment).merge(user_id: current_user.id)`
に変更しましょう

2020-11-03 10:38 UTC, nousi commented on app/controllers/posts_controller.rb
> +    @comments = @post.comments.order("created_at DESC")
includesをつけましょう
@post.comments.includes(:user)

2020-11-03 11:00 UTC, tattu501 commented on app/assets/stylesheets/comments.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
上記ファイルを削除しました。

2020-11-03 11:03 UTC, tattu501 commented on app/controllers/comments_controller.rb
> +  def create
before_action :authenticate_user!を追加しました。

2020-11-03 11:07 UTC, tattu501 commented on app/views/posts/show.html.erb
> +              <%= f.hidden_field :post_id, value: @post.id %>
user_idとpost_idのhidden_fieldを削除しました。

2020-11-03 11:08 UTC, tattu501 commented on app/controllers/comments_controller.rb
> +    @comment = current_user.comments.new(comment_params)
@comment = @post.comment.new(comment_params)に修正しました。

2020-11-03 11:13 UTC, tattu501 commented on app/controllers/comments_controller.rb
> +      params.require(:comment).permit(:comment, :user_id, :post_id)
params.require(:comment).permit(:comment).merge(user_id: current_user.id)に変更しました。

2020-11-03 11:15 UTC, tattu501 commented on app/controllers/posts_controller.rb
> +    @comments = @post.comments.order("created_at DESC")
includes(:user)を付与しました。

2020-11-03 11:31 UTC, tattu501 commented on app/controllers/comments_controller.rb
> +    @comment = current_user.comments.new(comment_params)
@comment = @post.comment.new(comment_params)だとエラーが発生したので、修正しました。
修正前）
@comment = @post.comment.new(comment_params)

修正後）
@post = Post.find(params[:post_id])
@comment = @post.comments.new(comment_params)

2020-11-03 12:17 UTC, nousi approved these changes

2020-11-03 12:17 UTC, nousi commented
LGTM

2020-11-04 13:00 UTC, sew-sou19 requested changes
レビュー完了しましたー！
修正お願いします！

2020-11-04 13:00 UTC, masato-sa93 commented on app/controllers/comments_controller.rb
> +      redirect_back(fallback_location: root_path)
ここで`redirect_back`を使っている理由はなんでしょうか？

`redirect_back`はRails5.1以降では非推奨のはずです。
https://qiita.com/100010/items/3ae5dea25e85b0cbf1ee

2020-11-04 13:00 UTC, masato-sa93 commented on app/controllers/posts_controller.rb
> +    @comment = @post.comments.build(user_id: current_user.id, post_id: @post.id) if current_user
`if current_user`の記述で、未ログイン時に投稿詳細ページに遷移したときにエラー出ないでしょうか？
出なければそのままでOKです。

2020-11-04 14:43 UTC, tattu501 commented on app/controllers/posts_controller.rb
> +    @comment = @post.comments.build(user_id: current_user.id, post_id: @post.id) if current_user
未ログイン時にもエラーが出ませんでした。なのでそのままにしました。

2020-11-04 14:44 UTC, tattu501 commented on app/controllers/comments_controller.rb
> +      redirect_back(fallback_location: root_path)
1つ前のページに戻るならredirect_backだと思ったからです。
上記の通り非推奨なので、redirect_toに変更しました。

2020-11-04 14:53 UTC, sew-sou19 approved these changes
LGTMですー！
早速の修正さすがです！

2020-11-05 14:45 UTC, merged