[WIP]コメント編集/削除機能(Comments.edit delete)
ozeryu7/tenkue-board-r006 pull request #13
Opened 2020-11-03 11:37 UTC by tattu501

#何か
投稿詳細ページからコメントの編集、削除する機能を追加

2020-11-03 21:23 UTC, ozeryu7 commented
LGTMです。

2020-11-04 13:14 UTC, sew-sou19 requested changes
レビュー完了しましたー！
修正お願いします

2020-11-04 13:14 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +    @post = Post.find(@comment.post_id)
`@post`のインスタンスを定義するコードが重複してるので、まとめてメソッドにしましょう！

2020-11-04 13:14 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +    comment_params[:post_id] = @comment.post_id
このコードの意味はなんでしょうか、、、？

2020-11-04 13:14 UTC, sew-sou19 commented on app/models/user.rb
> +  has_many :comments
こちらにも`dependent: :destroy`を記述しましょう！

2020-11-04 15:31 UTC, tattu501 commented on app/controllers/comments_controller.rb
> +    @post = Post.find(@comment.post_id)
＠postのインスタンスを定義するコードをメソッドにしました。

2020-11-04 15:36 UTC, tattu501 commented on app/controllers/comments_controller.rb
> +    comment_params[:post_id] = @comment.post_id
comment更新用のパラメータにpost_idが入っていないと思ったので、それを代入する処理を入れました。
この処理がなくても動いたので、コードを削除しました。

2020-11-04 15:38 UTC, tattu501 commented on app/models/user.rb
> +  has_many :comments
dependent: :destroyを追記しました。

2020-11-05 12:30 UTC, sew-sou19 requested changes
指摘の仕方が悪くて申し訳ありません！
もう一度修正をお願いしますー！

2020-11-05 12:30 UTC, sew-sou19 commented on app/controllers/comments_controller.rb
> +    @post = find_post(@comment.post_id)
あ、指摘の仕方が悪くて申し訳ありません。
メソッドにまとめて、before_actionで宣言すればコードの記述量が減らせるので、そっちの方法でお願いしたいです（この修正だとあまり意味がないので、、）

2020-11-05 13:08 UTC, nousi commented on app/controllers/comments_controller.rb
> +    @post = find_post(@comment.post_id)
```
before_action set_post

def set_post
  @post = Post.find(params[:id])
end
```

2020-11-05 13:38 UTC, tattu501 commented on app/controllers/comments_controller.rb
> +    @post = find_post(@comment.post_id)
before_actionに変更しました。

2020-11-05 13:47 UTC, sew-sou19 approved these changes
LGTM

2020-11-05 14:46 UTC, merged