[WIP]いいね機能
ozeryu7/tenkue-board-r006 pull request #14
Opened 2020-11-04 05:09 UTC by nousi

# 何か
ハートボタンを押すと、いいねが作成される。
いいね済みの場合は、いいねが削除される。
投稿された内容を評価するための機能。

# 変更箇所
- like.rbの作成
- likes_controller.rbの作成
- user.rbとpost.rbにlikeのリレーションを追加
- posts/show.html.erbにいいねボタンを実装
- posts/index.html.erbにいいねボタンを実装

2020-11-04 16:00 UTC, tattu501 commented on app/controllers/likes_controller.rb
> +  end
redirect_backはRails5.1以降だと非推奨らしいです。
可能ならばコードの修正をお願いします。

2020-11-04 16:07 UTC, tattu501 commented on app/models/post.rb
> +  has_many :likes
has_many :likesにdependent: :destroyを記述してください。

2020-11-04 16:08 UTC, tattu501 commented on app/models/user.rb
> +  has_many :likes
has_many :posts、has_many :likesにdependent: :destroyを記述してください。

2020-11-04 23:38 UTC, nousi commented on app/controllers/likes_controller.rb
> +  end
redirect_to :backが非推奨のようなので、このまま進めていきます

2020-11-04 23:39 UTC, nousi commented on app/models/user.rb
> +  has_many :likes
dependent: :destroy追加しました

2020-11-04 23:40 UTC, nousi commented on app/models/post.rb
> +  has_many :likes
dependent: :destroy追加しました

2020-11-05 00:20 UTC, tattu501 commented on app/controllers/likes_controller.rb
> +  end
redirect_toにすることは出来ますでしょうか？

2020-11-06 13:09 UTC, tattu501 commented on app/models/user.rb
> +  has_many :likes dependent: :destroy
has_many :posts、has_many :likesについて、dependent: :destroyの前にカンマがないことでSyntaxエラーとなっております。カンマを追記してください。

2020-11-06 13:10 UTC, tattu501 commented on app/models/post.rb
> +  has_many :likes dependent: :destroy
has_many :likesについて、dependent: :destroyの前にカンマがないことによりSyntaxエラーとなっております。
カンマを追記してください。

2020-11-06 13:14 UTC, nousi commented on app/models/user.rb
> +  has_many :likes dependent: :destroy
改善しました！

2020-11-06 13:14 UTC, nousi commented on app/models/post.rb
> +  has_many :likes dependent: :destroy
追加して改善しました

2020-11-06 13:16 UTC, tattu501 commented
LGTM

2020-11-06 13:37 UTC, sew-sou19 requested changes
レビューしました！
ご確認お願いしますー！！

2020-11-06 13:37 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    redirect_back(fallback_location: post_path(params[:post_id]))
以前も指摘しましたが、`redirect_back`は5.1以降は非推奨のはずですー！
これでないといけない理由があれば別ですが、そうでなければ推奨のヘルパーメソッドを使いましょう！

2020-11-06 13:37 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    @like = Like.find_by(user_id: current_user.id, post_id: @post.id)
destroyメソッドでは、インスタンス変数を定義する必要はないはずです（ビュー側に渡さないので）。
例えば以下の書き方などすれば記述量を減らせます！
```suggestion
    Like.find_by(id: params[:id]).destroy
```

2020-11-06 13:37 UTC, sew-sou19 commented on config/routes.rb
> +  resources :likes, only: [:create, :destroy]
likesのルーティングはpostsにネストしなくて問題なく動作しますか？
動作するならひとまずは問題ないです

2020-11-06 13:44 UTC, nousi commented on app/controllers/likes_controller.rb
> +    redirect_back(fallback_location: post_path(params[:post_id]))
redirect_to :backが非推奨ではなかったですか？
https://qiita.com/100010/items/3ae5dea25e85b0cbf1ee
https://railsdoc.com/page/redirect_back

2020-11-06 13:53 UTC, nousi commented on config/routes.rb
> +  resources :likes, only: [:create, :destroy]
動作します

2020-11-06 14:01 UTC, nousi commented on app/controllers/likes_controller.rb
> +    @like = Like.find_by(user_id: current_user.id, post_id: @post.id)
`Like.find_by(user_id: current_user.id, post_id: @post.id).destroy`に変更しました

Like.find_by(id: params[:id]).destroyの場合は、post_controller上で@likeを定義する必要があるので、そのままにしています。

2020-11-06 14:07 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    redirect_back(fallback_location: post_path(params[:post_id]))
ああああ！！！
ごめんなさい勘違いでした🙇‍♂️ご放念ください。

2020-11-06 14:07 UTC, sew-sou19 commented on app/controllers/likes_controller.rb
> +    @like = Like.find_by(user_id: current_user.id, post_id: @post.id)
了解ですー！

2020-11-06 14:07 UTC, sew-sou19 approved these changes
LGTMです！

2020-11-06 14:42 UTC, nousi commented on app/controllers/likes_controller.rb
> +    redirect_back(fallback_location: post_path(params[:post_id]))
これ誤解しやすいですよね😀

2020-11-07 01:49 UTC, merged