UserのRspec機能実装（user_spec.rb）
ozeryu7/tenkue-board-r006 pull request #16
Opened 2020-11-04 22:58 UTC by ozeryu7

#何か
UserのRspec機能実装します。

2020-11-06 12:17 UTC, tattu501 commented on spec/models/user_spec.rb
> +      end
以下の点をご確認の上、修正をお願いします。
上記の２ケースに共通する点
・無効なパスワードを確認するテストなので、タイトルの"valid"は"invalid"にする。

ケース：is valid with a password that has less than 8 characters
・８文字未満のパスワードが無効であることを確認 → テスト用のパスワードは７文字にする。

ケース：is valid with a password that has more than 32 characters
・３２文字超のパスワードが無効であることを確認 → テスト用のパスワードは３３文字にする。

2020-11-06 12:55 UTC, nousi commented on spec/models/user_spec.rb
> +      end
validをinvalidに変更しました！！
厳密に文字数を調整する必要はないと思うので、このままにさせてもらいます。

2020-11-06 12:56 UTC, tattu501 commented
LGTM

2020-11-06 13:04 UTC, sew-sou19 requested changes
レビュー完了しましたー！
さすがですが、もう少し追加でテスト書くとより良いのでご確認お願いします🙏

2020-11-06 13:04 UTC, sew-sou19 commented on spec/models/post_spec.rb
> +      end
「140文字以上の場合に登録できないこと」のテストも追加しましょうー！

2020-11-06 13:04 UTC, sew-sou19 commented on spec/models/user_spec.rb
> +    end
「パスワードが8文字以上32文字以下であれば登録できること」のテストも追加しましょうー！
文字数制限のバリデーションを設定した際は、閾値でcan/can't両方をテストするのがおすすめです

2020-11-06 13:17 UTC, nousi commented on spec/models/user_spec.rb
> +    end
Rspec__postで実施しています。

2020-11-06 13:17 UTC, nousi commented on spec/models/post_spec.rb
> +      end
Rspec__postで実施しています。

2020-11-06 13:21 UTC, nousi commented on spec/models/user_spec.rb
> +    end
Fackerでパスワードが8文字以上なので、8文字以上32文字以下はできていると思います。

2020-11-06 13:28 UTC, sew-sou19 reviewed
コメントしましたー！
ご確認お願いします！

2020-11-06 13:28 UTC, sew-sou19 commented on spec/models/post_spec.rb
> +      end
> Rspec__postで実施しています。

すいません、これどこのことでしょうか、、、？
リンクいただくかファイル名で指定していただけると幸いです🙏

2020-11-06 13:28 UTC, sew-sou19 commented on spec/models/user_spec.rb
> +    end
8文字はできてますが、32文字でも登録できるかがこのテストだと明確でないので、そこも合わせて記述してあげるとよいです！

こういう書き方もある！という一例です↓

```suggestion
      it "パスワード（password）         8文字以上かつ32文字以下で半角英数字両方を含んでいれば登録できること" do
        user = build(:user, password: "abcd1234" * 4 , password_confirmation: "abcd1234" * 4)
        expect(user).to be_valid
      end
```

2020-11-07 01:19 UTC, ozeryu7 commented on spec/models/post_spec.rb
> +      end
壮さん、以下プルリクのリンクで「140文字以上の場合に登録できないこと」のテスト実装しております。
ご確認お願いします！
[https://github.com/ozeryu7/tenkue-board-r006/pull/18](url)

2020-11-07 02:04 UTC, nousi commented on spec/models/user_spec.rb
> +    end
追加しました！
わかりやすく疑問が晴れました
ありがとうございます！

2020-11-07 02:13 UTC, nousi commented on spec/models/post_spec.rb
> +      end
#18 Postモデルのプルリクエストになります

2020-11-07 11:41 UTC, sew-sou19 approved these changes
LGTMですー！

2020-11-07 11:41 UTC, sew-sou19 commented on spec/models/post_spec.rb
> +      end
理解しました。
このプルリクはUserモデルのテストなんですね。
ここでのレビューはしないので、この指摘は無視してください。

繰り返しになりますが、YAGNI原則は意識しましょうー！
今はこの量の記述なので各々把握できるかもですが、実務量になると途端に把握できなくなります。
その際に、関係のない箇所を変更してしまうとデバッグが大変になるので、、、！

2020-11-07 12:13 UTC, merged