Origin/user.devise
ozeryu7/tenkue-board-r006 pull request #4
Opened 2020-10-26 22:01 UTC by ozeryu7

#何か
users_controllerを追加

#変更ファイル
こちらでは変更したファイルを解説します。

作成したファイル
app/assets/javascripts/users.coffee
app/assets/stylesheets/users.scss
app/helpers/users_helper.rb
app/controllers/users_controller.rb
test/controllers/users_controller_test.rb

2020-11-01 20:53 UTC, nousi requested changes

2020-11-01 20:53 UTC, msgyu commented on app/controllers/users_controller.rb
> +  end
今回はログイン/新規登録機能だけが必要なので、これらのアクションは不要となります。

2020-11-01 20:53 UTC, nousi commented on app/assets/javascripts/posts.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
不要なファイルの削除

2020-11-01 20:53 UTC, nousi commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
不要なファイルの削除

2020-11-01 20:53 UTC, nousi commented on app/assets/stylesheets/posts.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
不要なファイルの削除

2020-11-01 20:53 UTC, nousi commented on app/assets/stylesheets/users.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
不要なファイルの削除

2020-11-01 20:53 UTC, nousi commented on app/controllers/users_controller.rb
> +end
不要なコントローラーの削除

2020-11-02 09:57 UTC, ozeryu7 commented on app/controllers/users_controller.rb
> +  end
app/controllers/users_controller.rb 削除完了しました。

2020-11-02 09:57 UTC, ozeryu7 commented on app/assets/javascripts/posts.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
app/assets/javascripts/posts.coffee　削除完了しました。

2020-11-02 09:58 UTC, ozeryu7 commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
app/assets/javascripts/users.coffee　削除完了しました。

2020-11-02 09:58 UTC, ozeryu7 commented on app/assets/stylesheets/posts.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
app/assets/stylesheets/posts.scss　削除完了しました。

2020-11-02 09:58 UTC, ozeryu7 commented on app/assets/stylesheets/users.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
app/assets/stylesheets/users.scss　削除完了しました。

2020-11-02 09:58 UTC, ozeryu7 commented on app/controllers/users_controller.rb
> +end
app/controllers/users_controller.rb　削除完了しました。

2020-11-03 02:57 UTC, nousi commented on db/migrate/20201024140953_create_posts.rb
>    end
このファイルは不要なので、削除してください。
削除後は rake db:reset を実施してください

2020-11-03 04:21 UTC, nousi approved these changes

2020-11-03 04:22 UTC, nousi commented
LGTM

2020-11-03 07:37 UTC, ozeryu7 commented
LGTMです。

2020-11-03 08:35 UTC, sew-sou19 approved these changes
LGTMですー！
一発はさすがです！

2020-11-03 09:26 UTC, merged