[WIP]記事投稿の一覧作成(View)
ozeryu7/tenkue-board-r006 pull request #6
Opened 2020-10-27 23:25 UTC by nousi

#何か
記事一覧の作成をする

2020-10-31 02:09 UTC, tattu501 commented
LGTM

2020-10-31 15:20 UTC, sew-sou19 requested changes
コードは問題ないです！さすがですね。
不要なファイルの削除だけお願いします🙇‍♂️

2020-10-31 15:20 UTC, sew-sou19 commented on app/assets/stylesheets/posts.scss
> +// Place all the styles related to the posts controller here.
不要なファイルは混乱につながるので消しておきましょう！

2020-11-01 05:56 UTC, nousi commented on app/assets/stylesheets/posts.scss
> +// Place all the styles related to the posts controller here.
削除完了しました！

2020-11-01 10:36 UTC, sew-sou19 approved these changes
LGTMです！！

2020-11-02 01:56 UTC, merged