[WIP]新規投稿機能(Posts.create)の作成
ozeryu7/tenkue-board-r006 pull request #7
Opened 2020-10-30 13:21 UTC by tattu501

#何か
新規投稿のアクション、およびビューを追加

#変更ファイル
posts.controller.rb
posts/new.html.erb
posts/shared/_error_messages.html.erb
post.rb
Gemfile
Gemfile.lock
config/application.rb
config/locales/ja.yml

2020-11-01 06:11 UTC, nousi requested changes

2020-11-01 06:11 UTC, msgyu commented on app/assets/javascripts/posts.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
posts.coffeeファイルの削除

2020-11-01 06:11 UTC, msgyu commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
user.coffeeは使用しないので削除しましょう

2020-11-01 06:11 UTC, msgyu commented on app/assets/stylesheets/users.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
users.scssを削除しておきましょう

2020-11-01 06:11 UTC, msgyu commented on app/controllers/users_controller.rb
> +end
users_controller.rbの削除
今回は使用しません

2020-11-01 06:11 UTC, nousi commented on app/assets/stylesheets/posts.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
使用していないので、posts.scssを削除しておきましょう

2020-11-01 06:11 UTC, nousi commented on app/views/posts/_header.html.erb
> +</header>
このファイル削除しましょう。
partsフォルダに格納されている_header.html.erbは、sharedフォルダに移行完了済みです。
なので、partsフォルダに入っているheader.html.erbは古いのでこれを削除してください。

2020-11-01 06:11 UTC, nousi commented on db/migrate/20201030162743_add_user_id_to_posts.rb
> +end
不要なマイグレーションファイルなので、削除しましょう
削除完了後、rake db:reset を実施して、schemaを更新してください

2020-11-01 06:11 UTC, nousi commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2020_10_30_162743) do
使用していないmigrationファイルの日付になっているので、migrationファイル削除後、rake db:reset で更新し、日付を修正してください

2020-11-01 07:31 UTC, tattu501 commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
user.coffeeを削除しました。

2020-11-01 07:32 UTC, tattu501 commented on app/assets/stylesheets/users.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
users.scssを削除しました。

2020-11-01 07:32 UTC, tattu501 commented on app/controllers/users_controller.rb
> +end
users_controller.rbを削除しました。

2020-11-01 07:41 UTC, tattu501 commented on app/assets/stylesheets/posts.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
posts.scssを削除しました。

2020-11-01 07:42 UTC, tattu501 commented on app/views/posts/_header.html.erb
> +</header>
上記ファイルを削除しました。

2020-11-01 07:42 UTC, tattu501 commented on db/migrate/20201030162743_add_user_id_to_posts.rb
> +end
上記のマイグレーションファイルを削除しました。

2020-11-01 07:43 UTC, tattu501 commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2020_10_30_162743) do
申し訳ございません。マイグレーションファイルを削除後、rake db:reset をしましたが、日付が変わりませんでした。

2020-11-02 14:50 UTC, tattu501 commented on app/assets/javascripts/posts.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
申し訳ございません、コメントを失念しておりました。上記ファイルを削除しました。

2020-11-03 03:03 UTC, nousi commented
LGTM

2020-11-03 08:27 UTC, nousi approved these changes

2020-11-03 08:27 UTC, sew-sou19 approved these changes
LGTMですー！
おそらく別のプルリクをマージするとコンフリクト起こすので、そこを注意してください！

2020-11-03 08:31 UTC, merged