[WIP] Postの詳細画面を表示（posts.show)
ozeryu7/tenkue-board-r006 pull request #8
Opened 2020-10-30 16:18 UTC by nousi

#何か
投稿一覧から、投稿内容をクリックすると詳細画面に移行する。
![スクリーンショット 2020-10-31 1 17 59](https://user-images.githubusercontent.com/52862370/97730246-f646d600-1b16-11eb-9a8e-f460754a4903.png)

## 追加するファイル
- show.html.erb

2020-11-03 03:53 UTC, tattu501 commented on db/migrate/20201030162743_add_user_id_to_posts.rb
> +end
不要なマイグレーションファイルなので、削除をお願いいたします。
削除完了後、rake db:reset を実施して、schemaを更新してください。

2020-11-03 03:55 UTC, tattu501 commented on db/schema.rb
>    enable_extension "plpgsql"
使用していないmigrationファイルの日付になっているので、migrationファイル削除後、rake db:reset で更新し、日付を修正してください　※rake db:resetしても日付が修正されなければ、そのままでいいです。

2020-11-03 03:59 UTC, tattu501 commented
app/views/layouts/application.html.erb.tmpを削除してください。

2020-11-03 04:07 UTC, nousi commented on db/migrate/20201030162743_add_user_id_to_posts.rb
> +end
ファイルの削除完了
rails db:migrate:reset 実行

2020-11-03 04:07 UTC, nousi commented on db/schema.rb
>    enable_extension "plpgsql"
rails db:migrate:resetを実行し、2020_10_24の日付に戻しています

2020-11-03 04:11 UTC, tattu501 commented
LGTM

2020-11-03 08:09 UTC, ozeryu7 commented
LGTM

2020-11-03 13:16 UTC, sew-sou19 requested changes
レビュー完了しました！
いくつか修正あるのでご対応をお願いします！

2020-11-03 13:16 UTC, sew-sou19 commented on app/assets/stylesheets/users.scss
> +// Place all the styles related to the users controller here.
不要なCSSファイルは混乱を招くので削除しましょうー！

2020-11-03 13:16 UTC, sew-sou19 commented on app/assets/stylesheets/application.scss
> +@import "comments/comments";
ん？？なぜもうcommentsのCSSファイルが、、、
YAGNI原則もかなり大事なので、しっかりブランチ別に実装する機能を切り分けましょう！

2020-11-03 13:16 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +      @post = Post.includes(:user).find(params[:id])
この辺の指摘は前のプルリクで行ったんですが先祖返りしてますね、、、
森さんが`includes(:user)`はミスだったと修正されてるはずなので、そちらに合わせましょう！

2020-11-03 13:16 UTC, sew-sou19 commented on app/views/posts/show.html.erb
> +                <%= link_to "編集", "#" %></li>
編集と削除機能はすでに実装しているかと思うので、リンクを設置しましょうー！

2020-11-03 13:34 UTC, nousi commented on app/assets/stylesheets/users.scss
> +// Place all the styles related to the users controller here.
削除しました

2020-11-03 13:35 UTC, nousi commented on app/assets/stylesheets/application.scss
> +@import "comments/comments";
削除しました

2020-11-03 13:48 UTC, nousi commented on app/controllers/posts_controller.rb
> +      @post = Post.includes(:user).find(params[:id])
修正しました

2020-11-04 05:11 UTC, nousi commented
deleteとcreateメソッドをmergeする際にshowも一緒にマージしたため、このプルリクエストをクローズします。

2020-11-04 05:11 UTC, closed without merging