[WIP]掲示板編集／削除機能(Posts.edit&Posts.delete)
ozeryu7/tenkue-board-r006 pull request #9
Opened 2020-10-31 06:40 UTC by tattu501

#何か
投稿一覧、投稿詳細から編集と削除ができるようにする。

2020-11-01 06:32 UTC, nousi requested changes

2020-11-01 06:32 UTC, nousi commented on app/assets/javascripts/posts.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
不要なファイルの削除

2020-11-01 06:32 UTC, nousi commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
不要なファイルの削除

2020-11-01 06:32 UTC, nousi commented on app/assets/stylesheets/posts.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
不要なファイルの削除

2020-11-01 06:32 UTC, nousi commented on app/assets/stylesheets/users.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
不要なファイルの削除

2020-11-01 06:32 UTC, nousi commented on db/migrate/20201030162743_add_user_id_to_posts.rb
> +end
不要なマイグレーションファイル

2020-11-01 06:32 UTC, nousi commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2020_10_30_162743) do
不要なマイグレーションファイルを削除して、rake db:reset

2020-11-01 06:32 UTC, nousi commented on app/views/posts/show.html.erb
>            </ul>
view崩れ
</ul>の外に移動する必要があります。
元々は</ul>のあとに　<div class="post_detail__bottom_box__admin_actions">が存在していたが順序が逆になっている。
rails s でページを確認しながら修正してください

2020-11-01 09:32 UTC, tattu501 commented on app/assets/javascripts/posts.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
上記ファイルを削除しました。

2020-11-01 09:32 UTC, tattu501 commented on app/assets/javascripts/users.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
上記ファイルを削除しました。

2020-11-01 09:33 UTC, tattu501 commented on app/assets/stylesheets/posts.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
上記ファイルを削除しました。

2020-11-01 09:33 UTC, tattu501 commented on app/assets/stylesheets/users.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
上記ファイルを削除しました。

2020-11-01 09:33 UTC, tattu501 commented on db/migrate/20201030162743_add_user_id_to_posts.rb
> +end
上記ファイルを削除しました。

2020-11-01 09:33 UTC, tattu501 commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2020_10_30_162743) do
申し訳ございません。
マイグレーションファイル削除後にrake db:resetしましたが、日時が変わりませんでした。

2020-11-01 09:34 UTC, tattu501 commented on app/views/posts/show.html.erb
>            </ul>
ulのあとに　div class="post_detail__bottom_box__admin_actions"を移動しました。
また文字を青色にしました。

2020-11-01 20:57 UTC, nousi commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2020_10_30_162743) do
無事に動作し致命傷なるものではないので、このまま進めましょう

2020-11-01 20:59 UTC, nousi commented
LGTM

2020-11-02 00:56 UTC, sew-sou19 requested changes
レビュー完了しました。
修正後、再度依頼をお願いしますー！

2020-11-02 00:56 UTC, sew-sou19 commented on app/controllers/application_controller.rb
> +    added_attrs = [ :name, :email, :password ]
ここのkey指定はnameだけで大丈夫なはずですー！
（devise側でemailとpasswordは標準で準備してくれているので）

※列挙しても大丈夫と言えば大丈夫で好みの問題なので、修正しなくてもOKです

2020-11-02 00:56 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +  before_action :authenticate_admin!, except: [:index, :show, :new, :create]
exceptで4つアクションを指定するなら、onlyで3つ指定してあげた方が可読性高いと思いますー！

exceptは「〜を除く」で逆説的な意味合いなので、その文脈に合った使い方をすると読みやすいコードになります！

2020-11-02 00:56 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +      @post = Post.includes(:user).find(params[:id])
単一のpostインスタンスに、includesを記述してる意図って何かありますか？？

2020-11-02 00:56 UTC, sew-sou19 commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
usersコントローラーは何かに使ってますか？

2020-11-02 00:56 UTC, sew-sou19 commented on app/views/posts/edit.html.erb
> +      <%= form_for(@post) do |f| %>
Rails5.2以上の場合は`form_with`の方がベストプラクティスですー！

※`form_for`でも問題はないので、修正はしなくても大丈夫です。

2020-11-02 00:56 UTC, sew-sou19 commented on app/views/shared/_header.html.erb
> +<header class="header">
headerのビューファイルが2つできているので、不要な方を削除しましょう！

2020-11-02 01:52 UTC, nousi commented on app/views/posts/_header.html.erb
> +</header>
partsのheader.html.erbを削除

2020-11-02 01:52 UTC, nousi commented on app/controllers/users_controller.rb
> +end
users_controller.rbを削除

2020-11-03 00:16 UTC, tattu501 commented on app/controllers/application_controller.rb
> +    added_attrs = [ :name, :email, :password ]
key指定をnameのみに変更しました。

2020-11-03 01:01 UTC, tattu501 commented on app/controllers/posts_controller.rb
> +  before_action :authenticate_admin!, except: [:index, :show, :new, :create]
exceptからonlyに修正しました。

2020-11-03 01:08 UTC, tattu501 commented on app/controllers/posts_controller.rb
> +      @post = Post.includes(:user).find(params[:id])
includes(:user)は間違えて記述しておりました。
不要なので削除しました。

2020-11-03 01:10 UTC, tattu501 commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
使っている先はないです。不要なのでファイルを削除しました。

2020-11-03 01:12 UTC, tattu501 commented on app/views/posts/edit.html.erb
> +      <%= form_for(@post) do |f| %>
ご教示頂きありがとうございます。承知しました。

2020-11-03 01:16 UTC, tattu501 commented on app/views/shared/_header.html.erb
> +<header class="header">
app/views/posts/_header.html.erbが不要なので削除しました。

2020-11-03 01:16 UTC, tattu501 commented on app/views/posts/_header.html.erb
> +</header>
上記ファイルを削除しました。

2020-11-03 01:17 UTC, tattu501 commented on app/controllers/users_controller.rb
> +end
上記ファイルを削除しました。

2020-11-03 02:48 UTC, nousi commented on app/controllers/posts_controller.rb
> +  before_action :authenticate_admin!, only: [:edit, :update, :destroy]
before_action :authenticate_admin!, only: [:edit, :update, :destroy]を削除しましょう

before_action :authenticate_admin!, only: [:edit, :update, :destroy]
＞今回はuserモデルなので、before_action :authenticate_user!, except: [:index, :show]で統一しましょう。

before_action :authenticate_admin!の場合は、adminモデルである必要があります。
また、index,show以外はログイン認証が必要なので、

before_action :authenticate_user!, except: [:index, :show]だけで大丈夫です。

2020-11-03 02:49 UTC, nousi commented on app/controllers/posts_controller.rb
> +  before_action :authenticate_admin!, except: [:index, :show, :new, :create]
before_action :authenticate_admin!, except: [:index, :show, :new, :create]は不要なので、削除が必要です。
before_action :authenticate_user!, except: [:index, :show]をそのまま利用すれば問題ないです

2020-11-03 08:22 UTC, sew-sou19 approved these changes
LGTMですー！
さすがです！修正お疲れ様でした

2020-11-03 08:32 UTC, nousi approved these changes

2020-11-03 08:34 UTC, merged